### ISSUE TITLE
Null pointer

### ISSUE THREAD

**Issue by jbockerstette** [holidayextras/jsonapi-server#142]
/root/jsonapi-server/lib/routes/relationships.js:47
        sanitisedData = sanitisedData.relationships[request.params.relation].data;
                                     ^

TypeError: Cannot read property 'relationships' of null
    at /root/jsonapi-server/lib/routes/relationships.js:47:38
    at fn (/root/jsonapi-server/node_modules/async/lib/async.js:746:34)
    at /root/jsonapi-server/node_modules/async/lib/async.js:1213:16
    at /root/jsonapi-server/node_modules/async/lib/async.js:166:37
    at /root/jsonapi-server/node_modules/async/lib/async.js:706:43
    at /root/jsonapi-server/node_modules/async/lib/async.js:167:37
    at Immediate._onImmediate (/root/jsonapi-server/node_modules/async/lib/async.js:                                              1206:34)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)

**Comment by theninj4** [comment]
This occurs when the data coming out of your handler doesn't validate against your schema.

For example, if your Joi schema for a resource says `There will be a "body" attribute`, but the data in a database somewhere doesn't enforce the same requirement and someone inserts a row without a `body`, then you try and fetch that resource via the API.

I'm opening a PR in to provide an error saying "Sorry, this resource exists, but its fundamentally broken. We can't provide you with the resource because it won't conform to your expectations."

**Comment by theninj4** [comment]
Fixed in v1.11.0
