### ISSUE TITLE
Would it be reasonable to have a hook for a higher-level (graphql) ORM?

### ISSUE THREAD

**Issue by shaunc** [holidayextras/jsonapi-server#240]
We are building an analytics app, with an ember frontend. We need to support two types of data access: "metadata" -- users, various domain specific objects, etc. and "data" -- stuff we want to do analytics on.

jsonapi-server seems perfect to serve "metadata" to ember. For "data", the graphql interface would be very good. However, for bulk data access, it seems desirable to use something like [join-monster](https://github.com/stems/join-monster), as our backend is postgres. Is there a hook (or would the maintainers accept a hook as a PR and give me some guidance for where it should go :)) to register a "graphql-aware handler"?

**Comment by theninj4** [comment]
As of right now, there are no plans to give any special treatment to GraphQL (or JSON:API) in this project. The GraphQL layer (explained a little below)doesn't currently contain the first optimisation (below), but I'd choose implementing it better in this project as a preference over coupling resource handlers to the exposed data interface. 

The base querying in this project already contains a number of optimisations to make complex queries surprisingly efficient - JSON:API inclusions and fields enable a similar level of complexity as GraphQL queries (although they're far less readable) so we try and optimise as follows:

 * We try to only make a single "search" request for each resource. If we're fetching 20x sub resources off of 10x primary resources, we do a single search for all 200x resources (limiting the fields as requred) in one database query.
 * We don't ever join tables, we only query one resource at a time. This enables us to have a better understanding of the cost of queries because the query performance is largely consistent. We don't run the risk of a rogue user building up a query with so many joins that it hampers performance for others.

We already have a generic relational database storage handler that recieves the benefits of the above optimisations for JSON:API queries, and it should be possible given the GraphQL AST to apply the same optimisations to the GraphQL queries. Right now, we hook the resolvers up to blindly follow links (which pull data one ID at a time) whereas we should be parsing the AST to convert the GraphQL tree into a JSON:API query and then letting existing optimisations do the rest for us. The current resolver implementation is here: https://github.com/holidayextras/jsonapi-server/blob/master/lib/graphQl/resolvers.js#L10

**Comment by shaunc** [comment]
Hmm... this might be ok as a default strategy, but without joins it seems to me that you also run the risk of pulling in an arbitrary number of intermediate objects into application memory when traversing a many-to-many relationship which is filtered on the sub-resource. We will be needing to get max 10K-50K of objects back in a graphql query (and use a streaming interface to get them to the client, which is another issue).

Hmm... it looks like you pass the whole query to the handler in either case to get the parent resource. Perhaps a custom handler could signal that it has already dealt with the relationships? (E.g. by populating the fields?)

I guess in theory I could override some routes in a router (and you have a hook to pass in the router)? Seems pretty hacky, though. Perhaps a PR for per-resource override of route would be nice? Would be useful for streaming (which would have other uses -- /pictures/xQ==/getImage to execute some arbitrary method on a resource?)

**Comment by theninj4** [comment]
To be honest, I've not gotten to streaming (or pagination) of data from the GraphQl interface yet. In terms of performance of what's already there, I can share some metrics of one of our internal API's powered by this project, the data is backed by `jsonapi-store-relationaldb`, with a whole bunch of resources in a MySQL database running on a t2.medium in AWS (@ $0.047/hour) and it's currently underutilised for the current request volumes.

I don't know enough about GraphQl with respect to pagination and streaming, it's something we'll tackle when we need it.

If you want to stick with the library you referenced, you could fork this project and twiddle some things around for yourself. This code: (https://github.com/holidayextras/jsonapi-server/blob/master/lib/graphQl/readTypes.js#L43) is the GraphQl type where you'd be wanting to add the join conditions, and `resourceConfig` is the contents of the configuration in the resource definitions. You could then swap out the resolver for your libraries function.

**Comment by theninj4** [comment]
![screen shot 2017-01-05 at 14 31 27](https://cloud.githubusercontent.com/assets/3055120/21689668/ffa0f838-d368-11e6-8685-8e60ac551445.png)

**Comment by shaunc** [comment]
Thanks! 

jsonapi-server is a great fit for what I'm calling "metadata". For what I'm calling "data" we have some specialized needs. As you recommend we may try serving them separately for the moment. I'll get back to you if I figure out anything general.
