### ISSUE TITLE
how to use with mongoose?

### ISSUE THREAD

**Issue by futurist** [holidayextras/jsonapi-server#77]
I'm trying the lib and want to integrate with my existing mongoose Schema, like below:

````
var formTypeSchema = mongoose.Schema({

  name:{type:String},
  title:{type:String, default:''},
  mainKey:{type:String, default:'_id'},
  desc:{type:String, default:''},

  createAt:{ type: Date, default: function(){ return new Date() } },
  createBy:{type:_ObjectId , ref:'Person' },

  updateAt:{ type: Date, default: function(){ return new Date() } },
  updateBy:{type:_ObjectId , ref:'Person' },

  template: Mixed

})
````

with a sample data:
````
{
  name:"form1",
  title:"test for form1",
  template: { any:"object" }
}
````

trying but don't know where to start

**Comment by hxoliverrumbelow** [comment]
Hey @futurist. The goal of this project is to focus on defining/modeling json:api payloads rather than focusing on defining the backing data store. I've recently merged some changes to the README to explain the motivations behind a config-driven approach to building an API.

What does this mean for your use case? In a nutshell, you'll need to:

1. Define the resource's attributes that Clients will be interacting with - the docs [here](https://github.com/holidayextras/jsonapi-server/blob/master/documentation/resources.md) should help. 
2. Create/Pick a [handler](https://github.com/holidayextras/jsonapi-server/blob/master/documentation/handlers.md) - an object exposing operations to create/search/find/delete/update resources. If you're using mongodb you could consider using [jsonapi-store-mongodb](https://github.com/holidayextras/jsonapi-store-mongodb) which will deal with the mongodb storage layer for you.

The only difficulty you may run into will be around creation and updated dates. If you need to enforce those yourself (as in, you can't trust your clients to do it) you'll need to define your own handler to inject/update the dates into the users payloads before handing over to your data layer.

If all else fails, take a look over the example implementation (that uses the in-memory handler) here: https://github.com/holidayextras/jsonapi-server/tree/master/example

**Comment by futurist** [comment]
Thank you for the detailed reply. I've tried [json-api](https://github.com/ethanresnick/json-api), which using mongoose as store, but now I leave that lib and begin using jsonapi-server + jsonapi-sotre-mongodb, it's so far the best node lib to serve json-api IMO.

After test therer's an issue in my side:

### Source code:
````
var jsonApi = require("jsonapi-server");
var MongoStore = require("jsonapi-store-mongodb");

jsonApi.setConfig({
  base: "",
  port: 4000,
});

jsonApi.define({
  resource: "photos",
  handlers: new MongoStore({
    url: "mongodb://localhost:27017/test2",
  }),
  attributes: {
    title: jsonApi.Joi.string(),
    url: jsonApi.Joi.string().uri(),
    height: jsonApi.Joi.number().min(1).max(10000).precision(0),
    width: jsonApi.Joi.number().min(1).max(10000).precision(0)
  }
});

jsonApi.start();

````

### A. `POST` below data to url `/photos`
````
{"data":{"type":"photos","attributes":{"title":"test photo", "url":"http://www.baidu.com", "height":20, "width":30 }}}
````

### B. server returned body:
````
{"jsonapi":{"version":"1.0"},"meta":{},"links":{"self":"/photos/baff0a1d-5ad5-4042-abb2-5d9dfdbb571e"},"data":null}
````
here **data is null**;  but if changing `handlers: new jsonApi.MemoryHandler()` the data is right.

### C. check mongodb `test2` db, collections photos exists and contained a document as below
````
{ "_id" : BinData(4,"YmFmZjBhMWQtNWFkNS00MDQyLWFiYjItNWQ5ZGZkYmI1NzFl"), "id" : "baff0a1d-5ad5-4042-abb2-5d9dfdbb571e", "type" : "photos", "title" : "test photo", "url" : "http://www.baidu.com", "height" : 20, "width" : 30, "meta" : null }
````
but `GET` `/photos/baff0a1d-5ad5-4042-abb2-5d9dfdbb571e`, returned `data` is null

**Comment by futurist** [comment]
Beside, the project now need a feature, that user can interact with the data structure, similar to [typeform.com](http://www.typeform.com/)

The need is, in above **source code**, after `jsonApi.start()`, in a later time want to add a new resource type in `jsonApi.define`, e.g.:
````
jsonApi.start();

...... // at a later time
jsonApi.define({
  resource: "location",
  ....
})
jsonApi.close();
jsonApi.start();
// now there should have 2 resource types: photos, location
````
Question is: is this possible / right way to add new resources? any side effects except for the server down shortly?

**Comment by hxoliverrumbelow** [comment]
Hi @futurist - You can call `jsonApi.define()` whenever you like. `jsonApi.close()` is provided to enable all handlers to gracefully shutdown.
```
var jsonApi = require("jsonapi-server");

// jsonApi.define() here will work

jsonApi.setConfig({
  base: "",
  port: 4000,
});

// jsonApi.define() here will work

jsonApi.start();

// jsonApi.define() here will work
```

With regards to jsonapi-store-mongodb, it looks like you've found a bug. You can see the validation error if you start jsonapi-server using `DEBUG=jsonApi:*` as per the [debugging](https://github.com/holidayextras/jsonapi-server/blob/master/documentation/debugging.md) documentation.

The bug occurs because of the way MongoDB handles `null` and `undefined` values (undefined gets coerced to null, which fails the Joi validation). You can work around it for now by passing in an empty `meta` block:
```
$ curl -X POST --header "Content-Type: application/json" --data '{"data":{"type":"photos","attributes":{"title":"test photo", "url":"http://www.baidu.com", "height":20, "width":30}, "meta": { }}}' http://localhost:16006/rest/photos
```

Fixing the bug won't be too hard, we're currently pushing some more features into jsonapi-store-mongodb with the intention of putting it in production over the new few weeks. I'll add this bug to the todo-list.

**Comment by hxoliverrumbelow** [comment]
This one line fix: https://github.com/holidayextras/jsonapi-store-mongodb/pull/10/files#diff-4219f7be27f0b8a5bb43a23c247c204cR33 resolves the bug mentioned above.

**Comment by hxoliverrumbelow** [comment]
My updates have been merged, can you try again with `v1.1.0` of `jsonapi-store-mongodb`?

**Comment by futurist** [comment]
`POST` same test data above **without** `meta:{}`,  the returned JSON is right now:
````
{
  "jsonapi": {
    "version": "1.0"
  },
  "meta": {},
  "links": {
    "self": "/photos/008ef600-0cad-4fb5-860a-958414defde7"
  },
  "data": {
    "type": "photos",
    "id": "008ef600-0cad-4fb5-860a-958414defde7",
    "attributes": {
      "title": "test photo",
      "url": "http://www.baidu.com",
      "height": 20,
      "width": 30
    },
    "links": {
      "self": "/photos/008ef600-0cad-4fb5-860a-958414defde7"
    }
  }
}
````

But when `GET` `links.self` prop: /photos/008ef600-0cad-4fb5-860a-958414defde7, the returned JSON:

````
{
  "jsonapi": {
    "version": "1.0"
  },
  "meta": {},
  "links": {
    "self": "/photos008ef600-0cad-4fb5-860a-958414defde7"
  },
  "data": {
    "type": "photos",
    "id": "008ef600-0cad-4fb5-860a-958414defde7",
    "attributes": {
      "title": "test photo",
      "url": "http://www.baidu.com",
      "height": 20,
      "width": 30
    },
    "links": {
      "self": "/photos/008ef600-0cad-4fb5-860a-958414defde7"
    }
  },
  "included": []
}
````

the `links.self` lost a back-slash

**Comment by futurist** [comment]
Also noticed in the according mongodb document:
````
{ "_id" : BinData(4,"MDA4ZWY2MDAtMGNhZC00ZmI1LTg2MGEtOTU4NDE0ZGVmZGU3"), "id" : "008ef600-0cad-4fb5-860a-958414defde7", "type" : "photos", "title" : "test photo", "url" : "http://www.baidu.com", "height" : 20, "width" : 30 }
````
`_id` and `id` stored the same UUID in hex and string? can it only be one to optimize the doc size a little?

**Comment by theninj4** [comment]
When you set the config, I think you're missing some important bits, you'll need:
```
jsonApi.setConfig({
  protocol: "http",
  hostname: "localhost",
  port: 16006,
  base: "rest"
});
```
The missing config will make all the links absolute instead of relative and should fix up your issue.

I can see where you got the minimal config from, sorry about that, I'll raise an issue to update that example in the documentation.

**Comment by theninj4** [comment]
You're right about storing the `id` twice, it'd be great to only store it once. I'm going to leave that one until a colleague gets back from holiday, I'd like to run it by him before changing it. He might know something I don't.

**Comment by futurist** [comment]
If want to serve the api in a root path, say: `http://localhost:16006/photos` without `rest` in path, is that possible? 

I've tried ` base:"" ` and ` base:"/" `, both with a slash missing; the config you gave worked.

**Comment by theninj4** [comment]
Nice find again, it's fixed here: https://github.com/holidayextras/jsonapi-server/pull/79 from jsonapi-server v1.0.4 you'll be able to omit the `base` config and it'll behave as you expect.

**Comment by futurist** [comment]
According to the [JSON-API spec. 201 Create](http://jsonapi.org/format/#crud-creating-responses-201)
the response for create should be:
````
HTTP/1.1 201 Created
Location: http://example.com/photos/008ef600-0cad-4fb5-860a-958414defde7
````

but found now:
````
201 Created
Location: http://example.com/photos
````

**Comment by futurist** [comment]
In fact, in mongodb collection `photos`, both the `id` and `type` keys don't need to store, right?

**Comment by theninj4** [comment]
I've corrected the Location header: https://github.com/holidayextras/jsonapi-server/pull/80

Right now I'm not too worried about the mongo documents not being as efficient as possible on storage space. It's a trade-off between CPU processing time on the sever (removing + adding properties on every query, plus more logic to query differently as `id` wouldn't be a direct mapping) and storage space (storing an additional ~40 bytes per document). Storage space is really REALLY cheap at the moment, with 1,000,000 documents we're only looking at an additional 40MB of data storage.
