### ISSUE TITLE
How should we deal with pagination?

### ISSUE THREAD

**Issue by hxoliverrumbelow** [holidayextras/jsonapi-server#8]
* How should a data handler communicate to `jsonapi-server` "Here's the first 50 of 100 records"?
* How should we deal with pagination of included resources?
* Should we allow the first XX included resources and drop the rest?
* Should we error on the request if we can't fulfil every requested include?

**Comment by Artanis** [comment]
> How should a data handler communicate to jsonapi-server "Here's the first 50 of 100 records"?

`total` (records), `count` (records in page), `page` (current) and `pagecount` (total pages) in the `meta` object. Leave them there for the response, I'm sure someone will find them useful. Have the links generator build pagination links from it.

> How should we deal with pagination of included resources?

I'm given to understand that included resources must be linked from a resource in `data`, so if records are omitted from `data` by pagination, any records that would have been included by those omitted records are also omitted.

The specification suggests that included records can be paginated with paging links in the relationship's `links` object, maybe something like `/api/articles?page[reblog]=2&page[comments]=4`.

> Should we allow the first XX included resources and drop the rest?

Only if pagination is supported, otherwise some resources may become impossible to include.

> Should we error on the request if we can't fulfil every requested include?

If the client specifically requests the included records through the `include` parameter, I think pagination of included records is preferable to an error.

If If the request specifies which records to include, the server must send them. If you send an error because they are too many, it becomes impossible to access those records by inclusion.

The server gets to decide whether or not to make a compound document in the absence of that parameter, so if there are too many includes and no parameter it can just send the primary data.
